/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.*;
import javax.swing.event.TableColumnModelListener;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author justw
 */
public class AppWindow extends javax.swing.JFrame 
{
    /**
     * Creates new form JFrame
     */
    public AppWindow() {
        initComponents();
        Calculate_Update_Cost();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        CheckInPanel = new javax.swing.JPanel();
        NameField_CI = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NightsLabel = new javax.swing.JLabel();
        NightsComboBox = new javax.swing.JComboBox<>();
        OccupantsLabel = new javax.swing.JLabel();
        OccupantsComboBox = new javax.swing.JComboBox<>();
        RoomTypeLabel = new javax.swing.JLabel();
        RoomTypeComboBox = new javax.swing.JComboBox<>();
        ReservationCodeField = new javax.swing.JTextField();
        ReservationCodeLabel = new javax.swing.JLabel();
        CheckCodeButton = new javax.swing.JButton();
        HeadsupLabel = new javax.swing.JLabel();
        Tab1Title = new javax.swing.JLabel();
        CheckInButton = new javax.swing.JButton();
        MakeReservationButton = new javax.swing.JButton();
        CostLabel = new javax.swing.JLabel();
        costLabel2 = new javax.swing.JLabel();
        CheckOutPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NameLabel_CO = new javax.swing.JLabel();
        OR_Label = new javax.swing.JLabel();
        RoomNumberLabel_CO = new javax.swing.JLabel();
        NameField_CO = new javax.swing.JTextField();
        rNumCB_CO = new javax.swing.JComboBox<>();
        SearchButtonCO = new javax.swing.JButton();
        list1 = new java.awt.List();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        CheckOutButton = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        WindowColor = new javax.swing.JMenuItem();
        TextColor = new javax.swing.JMenuItem();
        TextOptions = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management");

        Tabs.setName("Check IN"); // NOI18N

        NameLabel.setText("Name");

        NightsLabel.setText("Nights");

        NightsComboBox.setMaximumRowCount(10);
        NightsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NightsComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NightsComboBoxPropertyChange(evt);
            }
        });

        OccupantsLabel.setText("Occupants");

        OccupantsComboBox.setMaximumRowCount(5);
        OccupantsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        RoomTypeLabel.setText("Room Type");

        RoomTypeComboBox.setMaximumRowCount(6);
        RoomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "King", "Queen", "Double", "KingSmoking", "QueenSmoking", "DoubleSmoking" }));
        RoomTypeComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                RoomTypeComboBoxPropertyChange(evt);
            }
        });

        ReservationCodeLabel.setText("Reservation Code");

        CheckCodeButton.setText("Check Code");
        CheckCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCodeButtonActionPerformed(evt);
            }
        });

        HeadsupLabel.setForeground(new java.awt.Color(255, 0, 0));
        HeadsupLabel.setText("If customer has a reservation code, enter it first. The information will be filled in for you.");

        Tab1Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab1Title.setText("CHECK IN OR MAKE RESERVATION");

        CheckInButton.setText("Check In");
        CheckInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInButtonActionPerformed(evt);
            }
        });

        MakeReservationButton.setText("Make Reservation");
        MakeReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeReservationButtonActionPerformed(evt);
            }
        });

        CostLabel.setText("Cost");

        costLabel2.setText("$0");

        javax.swing.GroupLayout CheckInPanelLayout = new javax.swing.GroupLayout(CheckInPanel);
        CheckInPanel.setLayout(CheckInPanelLayout);
        CheckInPanelLayout.setHorizontalGroup(
            CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CostLabel)
                            .addGroup(CheckInPanelLayout.createSequentialGroup()
                                .addComponent(CheckInButton)
                                .addGap(18, 18, 18)
                                .addComponent(MakeReservationButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CheckInPanelLayout.createSequentialGroup()
                                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                                        .addComponent(ReservationCodeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(ReservationCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                                        .addComponent(NameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NameField_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                                        .addComponent(NightsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(costLabel2)
                                            .addComponent(NightsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(HeadsupLabel))
                                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                                                .addComponent(OccupantsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(OccupantsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInPanelLayout.createSequentialGroup()
                                                .addComponent(RoomTypeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(CheckInPanelLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(Tab1Title))
                            .addComponent(CheckCodeButton))
                        .addGap(71, 71, 71))))
        );

        CheckInPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NameField_CI, NightsComboBox, OccupantsComboBox, RoomTypeComboBox});

        CheckInPanelLayout.setVerticalGroup(
            CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab1Title)
                .addGap(23, 23, 23)
                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationCodeLabel)
                    .addComponent(ReservationCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadsupLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckCodeButton)
                .addGap(18, 18, 18)
                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameField_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NightsLabel)
                            .addComponent(NightsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CheckInPanelLayout.createSequentialGroup()
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OccupantsLabel)
                            .addComponent(OccupantsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoomTypeLabel)
                            .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostLabel)
                    .addComponent(costLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInButton)
                    .addComponent(MakeReservationButton))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        Tabs.addTab("Check IN", CheckInPanel);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("CHECK OUT");

        NameLabel_CO.setText("Name");

        OR_Label.setText("OR");

        RoomNumberLabel_CO.setText("Room Number");

        rNumCB_CO.setMaximumRowCount(30);
        rNumCB_CO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        SearchButtonCO.setText("Search");
        SearchButtonCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonCOActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setEnabled(false);
        jScrollPane2.setViewportView(jList1);

        CheckOutButton.setText("Check Out");
        CheckOutButton.setEnabled(false);
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CheckOutPanelLayout = new javax.swing.GroupLayout(CheckOutPanel);
        CheckOutPanel.setLayout(CheckOutPanelLayout);
        CheckOutPanelLayout.setHorizontalGroup(
            CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutPanelLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CheckOutPanelLayout.createSequentialGroup()
                .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NameLabel_CO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CheckOutPanelLayout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(NameField_CO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(OR_Label)
                        .addGroup(CheckOutPanelLayout.createSequentialGroup()
                            .addComponent(RoomNumberLabel_CO)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rNumCB_CO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SearchButtonCO))
                .addGap(80, 80, 80)
                .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckOutButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 166, Short.MAX_VALUE))
            .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CheckOutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        CheckOutPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NameField_CO, rNumCB_CO});

        CheckOutPanelLayout.setVerticalGroup(
            CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CheckOutPanelLayout.createSequentialGroup()
                        .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel_CO)
                            .addComponent(NameField_CO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OR_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoomNumberLabel_CO)
                            .addComponent(rNumCB_CO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButtonCO)
                    .addComponent(CheckOutButton))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(CheckOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CheckOutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Tabs.addTab("Check OUT", CheckOutPanel);

        jScrollPane1.setEnabled(false);

        RoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RoomTable);

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabs.addTab("View Rooms", ViewPanel);

        jMenu1.setText("File");

        exitOption.setText("Exit");
        exitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionActionPerformed(evt);
            }
        });
        jMenu1.add(exitOption);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu3.setText("Colors");

        WindowColor.setText("Window Color");
        WindowColor.setToolTipText("");
        WindowColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindowColorActionPerformed(evt);
            }
        });
        jMenu3.add(WindowColor);

        TextColor.setText("Text Color");
        TextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextColorActionPerformed(evt);
            }
        });
        jMenu3.add(TextColor);

        jMenu2.add(jMenu3);

        TextOptions.setText("Text");
        TextOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOptionsActionPerformed(evt);
            }
        });
        jMenu2.add(TextOptions);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //my custom helper code
    
    private Boolean CheckRoomEmpty(int x) //implement!
    {
        return true;
    }
    
    ArrayList<HotelRoom>roomsVec = new ArrayList<>();
    ArrayList<HotelRoom>reservationVec = new ArrayList<>();
    static ArrayList<BasicRoomInfo>infoVec = new ArrayList<>();
    static final int MAXROOMS = 60;
    HotelRoom tempRoom = null;
    DefaultListModel listModel = new DefaultListModel();
    ArrayList<String>resCodes = new ArrayList<>();
    TableColumnModel tableModel = new TableColumnModel() {
        @Override
        public void addColumn(TableColumn aColumn) {
            tableModel.addColumn(aColumn);
        }

        @Override
        public void removeColumn(TableColumn column) {
            tableModel.removeColumn(column);
        }

        @Override
        public void moveColumn(int columnIndex, int newIndex) {
            tableModel.moveColumn(columnIndex, newIndex);
        }

        @Override
        public void setColumnMargin(int newMargin) {
            tableModel.setColumnMargin(newMargin);
        }

        @Override
        public int getColumnCount() {
            return tableModel.getColumnCount();
        }

        @Override
        public Enumeration<TableColumn> getColumns() {
            return tableModel.getColumns();
        }

        @Override
        public int getColumnIndex(Object columnIdentifier) {
            return tableModel.getColumnIndex(columnIdentifier);
        }

        @Override
        public TableColumn getColumn(int columnIndex) {
            return tableModel.getColumn(columnIndex);
        }

        @Override
        public int getColumnMargin() {
           return tableModel.getColumnMargin();
        }

        @Override
        public int getColumnIndexAtX(int xPosition) {
            return tableModel.getColumnIndexAtX(xPosition);
        }

        @Override
        public int getTotalColumnWidth() {
           return tableModel.getTotalColumnWidth();
        }

        @Override
        public void setColumnSelectionAllowed(boolean flag) {
            tableModel.setColumnSelectionAllowed(flag);
        }

        @Override
        public boolean getColumnSelectionAllowed() {
            return tableModel.getColumnSelectionAllowed();
        }

        @Override
        public int[] getSelectedColumns() {
            return tableModel.getSelectedColumns();
        }

        @Override
        public int getSelectedColumnCount() {
            return tableModel.getSelectedColumnCount();
        }

        @Override
        public void setSelectionModel(ListSelectionModel newModel) {
            tableModel.setSelectionModel(newModel);
        }

        @Override
        public ListSelectionModel getSelectionModel() {
            return tableModel.getSelectionModel();
        }

        @Override
        public void addColumnModelListener(TableColumnModelListener x) {
            tableModel.addColumnModelListener(x);
        }

        @Override
        public void removeColumnModelListener(TableColumnModelListener x) {
            tableModel.removeColumnModelListener(x);
        }
    };
    
    public int GetRoomNumber(HotelRoom.RoomType type)
    {
        int x = -999;
        Boolean found = false;
        for(int i = 0; i < MAXROOMS; i++)
        {
            if(!found){
                if(infoVec.get(i).type==type && !infoVec.get(i).filled)
                {
                    x = i+1;
                    found = true;
                    infoVec.get(i).SetFilled(found);
                }
            }
        }
        return x;
    }
    
    public void Calculate_Update_Cost()
    {
        int n = Integer.parseInt(NightsComboBox.getSelectedItem().toString());
        HotelRoom.RoomType t = HotelRoom.RoomType.valueOf(RoomTypeComboBox.getSelectedItem().toString());
        int c = HotelRoom.Cost(t);
        costLabel2.setText("$"+String.valueOf(n*c));
    }
    
    public HotelRoom Search(String s, int n)
    {
        if(s.isBlank())
        {
            for(int i = 0; i < roomsVec.size();i++)
            {
                if(roomsVec.get(i).roomNumber == n)
                {
                    return roomsVec.get(i);
                }
            }
        }
        else if (n==1 && !s.isBlank())
        {
            for(int i = 0; i < roomsVec.size();i++)
            {
                if(roomsVec.get(i).customerName.equalsIgnoreCase(s))
                {
                    return roomsVec.get(i);
                }
            }
        }
        return null;
    }
    
    private static final String ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    public static String GenerateRCode(int count) 
    {
    StringBuilder builder = new StringBuilder();
    while (count-- != 0) 
    {
        int character = (int)(Math.random()*ALPHA_NUMERIC_STRING.length());
        builder.append(ALPHA_NUMERIC_STRING.charAt(character));
    }
    return builder.toString();
}
    
    //code for when user clicks exit option
    private void exitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitOptionActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(CheckOutPanel, "Are you sure you want to check this person out?");
        if(option==JOptionPane.YES_OPTION)
        {
            roomsVec.remove(tempRoom);
            tempRoom=null;
            listModel.clear();
            CheckOutButton.setEnabled(false);
            NameField_CO.setText("");
        }
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void SearchButtonCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonCOActionPerformed
        NameField_CO.setText("");
        listModel.clear();
        String s = NameField_CO.getText();
        int n = Integer.parseInt(rNumCB_CO.getSelectedItem().toString());
        HotelRoom h = null;
        if(!roomsVec.isEmpty())
        {
            h = Search(s,n);
            tempRoom = Search(s,n);
            jList1.setModel(listModel);
            listModel.addElement("Name: " + h.customerName);
            listModel.addElement("Room Number: " +h.roomNumber);
            listModel.addElement("Room Type: " + h.getRoomType().toString());
            jList1.validate();
            CheckOutButton.setEnabled(true);
        }
        else
        JOptionPane.showMessageDialog(CheckOutPanel,"There is nobody checked in!");
    }//GEN-LAST:event_SearchButtonCOActionPerformed

    private void MakeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeReservationButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(CheckInPanel, "Are these details correct?");
        if(option==JOptionPane.YES_OPTION)
        {
            String name = NameField_CI.getText();
            int occ = Integer.parseInt(OccupantsComboBox.getSelectedItem().toString());
            int nights = Integer.parseInt(NightsComboBox.getSelectedItem().toString());
            HotelRoom.RoomType type = HotelRoom.RoomType.valueOf(RoomTypeComboBox.getSelectedItem().toString());
            int rNum = -1;
            if(!name.isBlank())
                rNum = GetRoomNumber(type);
            HotelRoom room = new HotelRoom(name,occ,rNum,type,nights);
            reservationVec.add(room);
            String temp = GenerateRCode(15);
            JOptionPane.showConfirmDialog(CheckInPanel, temp,"Customer's Reservation Code",-1);
            System.out.println(temp);
            room.setRCode(temp);
            System.out.println(room.getRCode());
            if(!reservationVec.isEmpty()){
                JOptionPane.showMessageDialog(CheckInPanel,"Reservation successful!");
                NameField_CI.setText("");
                NightsComboBox.setSelectedIndex(0);
                RoomTypeComboBox.setSelectedIndex(0);
                OccupantsComboBox.setSelectedIndex(0);
                Calculate_Update_Cost();
            }
        }
    }//GEN-LAST:event_MakeReservationButtonActionPerformed

    private void CheckInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(CheckInPanel, "Are these details correct?");
        if(option==JOptionPane.YES_OPTION)
        {
            String name = NameField_CI.getText();
            int occ = Integer.parseInt(OccupantsComboBox.getSelectedItem().toString());
            int nights = Integer.parseInt(NightsComboBox.getSelectedItem().toString());
            HotelRoom.RoomType type = HotelRoom.RoomType.valueOf(RoomTypeComboBox.getSelectedItem().toString());
            int rNum = -1;
            HotelRoom room = null;
            if(!name.isBlank())
                rNum = GetRoomNumber(type);
            if (!ReservationCodeField.getText().isBlank())
                room = tempRoom;
            else
                room = new HotelRoom(name,occ,rNum,type,nights);
            if(rNum!=-999 && !name.isBlank())
            {
                roomsVec.add(room);
                if(!roomsVec.isEmpty()){
                    JOptionPane.showMessageDialog(CheckInPanel,"Check in successful!");
                    //reset all fields
                    NameField_CI.setText("");
                    NightsComboBox.setSelectedIndex(0);
                    RoomTypeComboBox.setSelectedIndex(0);
                    OccupantsComboBox.setSelectedIndex(0);
                    //update the cost label
                    Calculate_Update_Cost();
                    //checking if a reservation code was used
                    tempRoom = null;
                    room.setRCode("");
                }
            }
            else
            {
                if(rNum==-999)
                    JOptionPane.showMessageDialog(CheckInPanel,"No rooms of this type available!");
                if(name.isBlank() || rNum == -1)
                    JOptionPane.showMessageDialog(CheckInPanel,"Name can't be empty!");
            }
        }
        NameField_CI.setText("");
        ReservationCodeField.setText("");
    }//GEN-LAST:event_CheckInButtonActionPerformed

    private void RoomTypeComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_RoomTypeComboBoxPropertyChange
        Calculate_Update_Cost();
    }//GEN-LAST:event_RoomTypeComboBoxPropertyChange

    private void NightsComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NightsComboBoxPropertyChange
        Calculate_Update_Cost();
    }//GEN-LAST:event_NightsComboBoxPropertyChange

    private void CheckCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCodeButtonActionPerformed
        String s = ReservationCodeField.getText();
        if(s.isBlank())
            return;
        Boolean found = false;
        for(HotelRoom h:reservationVec)
        {
            if(!found)
            {
                if(h.getRCode().equals(s))
                {
                    found = true;
                    NameField_CI.setText(h.getCustomerName());
                    NightsComboBox.setSelectedIndex(h.getNumNights()-1);
                    OccupantsComboBox.setSelectedIndex(h.getNumOccupants()-1);
                    RoomTypeComboBox.setSelectedItem(h.getRoomType().toString());
                    tempRoom = h;
                }
            }
        }
        if(!found)
            JOptionPane.showMessageDialog(CheckInPanel,"Reservation code not found!");
    }//GEN-LAST:event_CheckCodeButtonActionPerformed

    private void TextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextColorActionPerformed
        Color color = JColorChooser.showDialog(CheckInPanel,"Pick a text color", ReservationCodeField.getForeground());
        //Check In panel
        ReservationCodeField.setForeground(color);
        ReservationCodeLabel.setForeground(color);
        NameLabel.setForeground(color);
        NightsLabel.setForeground(color);
        OccupantsLabel.setForeground(color);
        CostLabel.setForeground(color);
        costLabel2.setForeground(color);
        RoomTypeLabel.setForeground(color);
        OccupantsComboBox.setForeground(color);
        RoomTypeComboBox.setForeground(color);
        NightsComboBox.setForeground(color);
        NameField_CI.setForeground(color);
        CheckCodeButton.setForeground(color);
        CheckInButton.setForeground(color);
        MakeReservationButton.setForeground(color);
        Tab1Title.setForeground(color);
        //Check Out Panel
        jLabel3.setForeground(color);
        NameLabel_CO.setForeground(color);
        OR_Label.setForeground(color);
        RoomNumberLabel_CO.setForeground(color);
        NameField_CO.setForeground(color);
        rNumCB_CO.setForeground(color);
        jList1.setForeground(color);
        CheckOutButton.setForeground(color);
        SearchButtonCO.setForeground(color);
        //view Panel
    }//GEN-LAST:event_TextColorActionPerformed

    private void TextOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOptionsActionPerformed
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] array = ge.getAvailableFontFamilyNames();
        JComboBox<String> box = new JComboBox<String>(array);
        box.setEditable(true);

        JFrame frame = new JFrame();

        JButton button = new JButton("Button");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(frame, box, "...", JOptionPane.QUESTION_MESSAGE);
                System.out.println(box.getSelectedItem());
            }
        });

        frame.getContentPane().add(button);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
    }//GEN-LAST:event_TextOptionsActionPerformed

    private void WindowColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindowColorActionPerformed
        Color color = JColorChooser.showDialog(CheckInPanel,"Pick a window color", CheckInPanel.getBackground());
        CheckInPanel.setBackground(color);
        CheckOutPanel.setBackground(color);
        ViewPanel.setBackground(color);
    }//GEN-LAST:event_WindowColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
            javax.swing.UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppWindow().setVisible(true);
            }
        });
        HotelRoom.RoomType[] roomarr = 
        {
            HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,
            HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,HotelRoom.RoomType.King,
            HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,
            HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,HotelRoom.RoomType.Queen,
            HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,
            HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,HotelRoom.RoomType.Double,
            HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,
            HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,HotelRoom.RoomType.KingSmoking,
            HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,
            HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,HotelRoom.RoomType.QueenSmoking,
            HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,
            HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking,HotelRoom.RoomType.DoubleSmoking
        };
        for(int i = 0; i < MAXROOMS;i++)
        {
            infoVec.add(new BasicRoomInfo(i,false,roomarr[i]));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckCodeButton;
    private javax.swing.JButton CheckInButton;
    private javax.swing.JPanel CheckInPanel;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JPanel CheckOutPanel;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JLabel HeadsupLabel;
    private javax.swing.JButton MakeReservationButton;
    private javax.swing.JTextField NameField_CI;
    private javax.swing.JTextField NameField_CO;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel_CO;
    private javax.swing.JComboBox<String> NightsComboBox;
    private javax.swing.JLabel NightsLabel;
    private javax.swing.JLabel OR_Label;
    private javax.swing.JComboBox<String> OccupantsComboBox;
    private javax.swing.JLabel OccupantsLabel;
    private javax.swing.JTextField ReservationCodeField;
    private javax.swing.JLabel ReservationCodeLabel;
    private javax.swing.JLabel RoomNumberLabel_CO;
    private javax.swing.JTable RoomTable;
    private javax.swing.JComboBox<String> RoomTypeComboBox;
    private javax.swing.JLabel RoomTypeLabel;
    private javax.swing.JButton SearchButtonCO;
    private javax.swing.JLabel Tab1Title;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JMenuItem TextColor;
    private javax.swing.JMenuItem TextOptions;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JMenuItem WindowColor;
    private javax.swing.JLabel costLabel2;
    private javax.swing.JMenuItem exitOption;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.List list1;
    private javax.swing.JComboBox<String> rNumCB_CO;
    // End of variables declaration//GEN-END:variables
}
